version: '3'

volumes:
  pgdata:
    external: false

services:
  database:
    env_file:
      - prod.env
    image: postgres:10.4-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  docs:
    image: sebp/lighttpd
    volumes:
      - ./doc/:/var/www/localhost/htdocs
    ports:
      - "80:80"
  amethyst:
    env_file:
      - prod.env
    depends_on:
      - database
    ports:
      - "7171:7171"
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bin/amethyst foreground"
