apiVersion: v1
kind: Service
metadata:
  name: amethyst-database-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: amethyst-database
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amethyst-database-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amethyst-database
    spec:
      volumes:
        - name: pgdata
          hostPath:
            path: /home/fschuindt/apps/stone/amethyst/pgdata
            type: Directory
      containers:
        - name: database
          image: postgres:10.4-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: pgdata
          env:
            - name: PG_DATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_HOST
              value: "database"
            - name: POSTGRES_DB
              value: "amethyst"
            - name: POSTGRES_USER
              value: "amethyst"
            - name: POSTGRES_PASSWORD
              value: ""
