apiVersion: v1
kind: Service
metadata:
  name: amethyst-database
spec:
  type: LoadBalancer
  ports:
    - port: 30032
      targetPort: 5432
      protocol: TCP
  selector:
    app: amethyst-database
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amethyst-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amethyst-database
    spec:
      containers:
        - name: database
          image: postgres:10.4-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST
              value: "database"
            - name: POSTGRES_DB
              value: "amethyst"
            - name: POSTGRES_USER
              value: "amethyst"
            - name: POSTGRES_PASSWORD
              value: ""
