apiVersion: v1
kind: Service
metadata:
  name: amethyst-docs
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: amethyst-docs
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amethyst-docs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amethyst-docs
    spec:
      volumes:
        - name: htdocs
          hostPath:
            path: /home/fschuindt/apps/stone/amethyst/doc
            type: Directory
      containers:
        - name: docs
          image: sebp/lighttpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/localhost/htdocs
              name: htdocs

