apiVersion: v1
kind: Service
metadata:
  name: amethyst-docs
spec:
  type: NodePort
  ports:
    - nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: amethyst-docs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amethyst-docs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amethyst-docs
    spec:
      containers:
        - name: docs
          image: localhost:5000/amethyst_documentation:latest
          ports:
            - containerPort: 80
