apiVersion: v1
kind: Service
metadata:
  name: amethyst-app
spec:
  type: NodePort
  ports:
    - nodePort: 30071
      port: 7171
      protocol: TCP
  selector:
    app: amethyst-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: amethyst-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amethyst-app
    spec:
      containers:
        - name: amethyst
          image: localhost:5000/amethyst_app:latest
          ports:
            - containerPort: 7171
          args: ["bash", "-c", "bin/amethyst foreground"]
          env:
            - name: REPLACE_OS_VARS
              value: "true"
            - name: RELEASE_PROD_COOKIE
              value: "rel_prod_cookie"
            - name: SENTRY_DSN
              value: "sentry_error_tracking_dsn"
            - name: POSTGRES_HOST
              value: "database"
            - name: POSTGRES_DB
              value: "amethyst"
            - name: POSTGRES_USER
              value: "amethyst"
            - name: POSTGRES_PASSWORD
              value: ""
